name: new_practice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^1.7.4
  bloc: ^6.1.1
  bubble: ^1.1.9+1
  carousel_slider: ^3.0.0
  chips_choice: ^2.0.1
  cloud_firestore: ^0.14.3+1
  cupertino_icons: ^1.0.0
  dash_chat: ^1.1.15
  extended_image: ^1.6.0
  # intl: ^0.16.1
  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.3
  firebase_messaging: ^8.0.0-dev.10
  firebase_storage: ^5.0.1
  floating_search_bar: ^0.3.0
  flutter_bloc: ^6.1.1
  flutter_credit_card: ^0.1.4
  flutter_custom_clippers: ^1.0.1
  flutter_downloader: ^1.5.2
  flutter_easyloading: ^2.2.2
  flutter_facebook_login: ^2.0.1
  flutter_form_builder: ^4.2.0
  flutter_gradient_colors: ^1.0.0
  flutter_inner_drawer: ^0.5.7+2
  flutter_local_notifications: ^4.0.1+2
  flutter_modular: ^2.0.1
  flutter_native_splash: ^0.3.0
  flutter_platform_widgets: ^0.72.0
  flutter_polyline_points: ^0.2.4
  flutter_staggered_grid_view: ^0.3.4
  flutter_svg: ^0.19.0
  flutter_typeahead: ^1.9.1
  fluttertoast: ^6.0.0
  freezed: ^0.12.7
  geolocator: ^6.2.0
  google_maps_flutter: ^1.2.0
  google_sign_in: ^4.5.9
  hive: ^1.5.0-pre
  http: ^0.12.2
  hydrated_bloc: ^6.1.0
  image_picker: ^0.6.7+22
  infinite_scroll_pagination: ^2.3.0
  introduction_screen: ^1.0.9
  jitsi_meet: ^2.0.0
  json_serializable: ^3.5.1
  lint: ^1.3.0
  logger: ^0.9.4
  login_fresh: ^1.0.8
  material_floating_search_bar: ^0.2.6
  ntp: ^1.0.8
  path_provider: ^1.6.28
  persistent_bottom_nav_bar: ^3.1.0
  pin_code_fields: ^6.1.0
  qr_code_scanner: ^0.3.5
  qr_flutter: ^3.2.0
  rxdart: ^0.25.0
  shimmer: ^1.1.2
  sizer: ^1.1.8
  sliding_sheet: ^0.4.0
  smart_select: ^4.3.2
  stepper_counter_swipe: ^1.0.0
  stripe_payment: ^1.0.11
  time: ^1.3.0
  url_launcher: ^5.7.10
  uuid: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  hive_generator: ^0.8.2
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/icon.png'
flutter_native_splash:
  color: "#ffffff"
  background_image: 'assets/images/splash.png'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your appli♂tion, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Brand-Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
    - family: Brand Bold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
